flags = [
    "zvwy ef {qjiwulkhodhsij}",
    "opqg dr {vnsjtljkpaogwb}",
    "iwrl fu {bqwtuprfslztyv}",
    "qxnm vz {ftxawivkghjmpe}",
    "vyiq jl {apmjweremzxrsn}",
    "ptuo rk {yfpkjvlcgigslh}",
    "lqdi sv {aeshtrrcmopwfj}",
    "kbgw vb {qpxunqfqizrszt}",
    "gxyf et {zhhmdoygzrhbxa}",
    "cuob mu {xjoduegcozckbm}",
    "qzxi fo {gfdjmikcypkmwd}",
    "ryfl ip {nczjnhxctkbsmk}",
    "hpmq nk {vrcrgfgeptgtay}",
    "wzya qt {bgqcjrcuxtvoin}",
    "mixg tp {oropjdefqjntpu}",
    "nxzy lz {rsuiovuhfzkfva}",
    "ucsf dw {tpecdygtkjhkne}",
    "gkwl ap {zzwifpqhvfrzjl}",
    "bvye em {wyobzjffdmuvhy}",
    "qals vu {tynhosbvqhlwwj}",
    "jtyc wl {fqkzicprlfnmoh}",
    "pzsi tn {wecbyrdcuqguba}",
    "kxom gk {zrdtntkxotqdr}",
    "fhnz eu {jsdrxteojqkdec}",
    "osla ny {bcxzmjzxygptke}",
    "lygf zb {wcfstkeccieysl}",
    "ntob og {zokvfziyyuxmnp}",
    "hxdt iw {qnlmlqzlkexkff}",
    "oeyc ht {hkvkgeviqdgcnq}",
    "enlu xm {nuupqlxjbbdnex}",
    "tfro ck {kldrvzzphwjpdg}",
    "mjke uc {whqgvltybcbfez}",
    "wqxo qg {fgcqrbzlyxdlaw}",
    "yikb jy {zwhpftubzmyykv}",
    "azep mc {pxtqupkqcqysrz}",
    "gbwv yw {hgtfozdnpnwhay}",
    "ksqo zm {kjwvzvnuwgckxn}",
    "hdox ni {uwnecscihnqumd}",
    "ryba bv {ktcvzrkzvczfdw}",
    "tkpw dt {jsilmlqazmszge}",
    "fwdu xj {bhtxvnpoxdjvvl}",
    "yqmw cx {kveleklknpycqg}",
    "rjof vt {jrhwqcbpplkhpd}",
    "uzid su {mqtpfrjholkgxh}",
    "syfw qa {qtiknzaqfckzqw}",
    "quhp tj {hsqwgbtsdmkydd}",
    "xvjt oe {lfjhnnhpbjjstf}",
    "zoeb vj {wroncskpmbtddg}",
    "zmru wr {gboebtmqhaytfo}",
    "vwqj ph {sfrkjyjhgcyqte}",
    "ntio qa {kimaiztqsmixxtm}"
]

dictionary = ["the", "be", "to", "of", "and", "a", "is", "that", "have", "it",
    "you", "he", "at", "by", "this", "but", "not", "from", "or", "which",
    "one", "would", "all", "will", "there", "say", "who", "for", "on", "we",
    "an", "she", "it", "my", "they", "them", "their", "so", "if", "up",
    "out", "about", "do", "no", "more", "like", "when", "get", "can",
    "what", "just", "has", "where", "into", "could", "then", "after", "over",
    "than", "some", "now", "how", "time", "two", "its", "these", "see",
    "him", "her", "we", "us", "your", "any", "no", "most", "up", "out",
    "know", "take", "good", "great", "want", "make", "work", "tell", "feel",
    "see", "give", "go", "come", "look", "think", "back", "day", "life"]

alphabet = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
